config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  post '/score', to: 'games#score', as: 'score'
  get '/new', to: 'games#new', as: 'new'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
require 'json'
require 'open-uri'

class GamesController < ApplicationController
  def new
    @letters = ('A'..'Z').to_a.sample(10)
  end

  def score
    # line 10 to 16 checking if its english word
    @words = params[:new]
    url = "https://wagon-dictionary.herokuapp.com/:score"
    word_serialized = URI.open(url).read
    api_reply = JSON.parse(word_serialized)
    # api_reply["found"]
    # found through api
    correct_word = api_reply["found"]
    raise
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/new.html.erb
<h1>New game</h1>
<ul>
  <% @letters.each do |letter| %>
    <li class="btn btn-primary"><%= letter %></li>
  <% end %>
</ul>

<h2>What is the longest word you can find?</h2>
<form action='/score', method='post' data-turbo="false">
  <input type="text" name="new">
  <input type="submit" value="Play">
  <input type= >
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
</form>

app/views/games/score.html.erb
<h1>Result</h1>

<p> Sorry but @letters can't be built out of ... </p>

<%= link_to 'Play again', games_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>